function main()
	%initData();
	data = getData();
	[trainingdata, testingdata] = splitEachLabel(data, 15000, "randomized");
	layers = [
    		imageInputLayer([128, 128, 3])
    		convolution2dLayer(5,20)
    		batchNormalizationLayer
    		reluLayer
    		fullyConnectedLayer(14)
    		softmaxLayer
	];
	options = trainingOptions("sgdm", MaxEpochs=200, Verbose=true, Plots="training-progress", Metrics="accuracy");
	%make the net
	%finalnet = trainnet(trainingdata, layers, "crossentropy", options);
	load finalnet;
	finalnet = trainnet(trainingdata, finalnet, "crossentropy", options);

	%store the net
	save finalnet;
end

function initData()
	%initialization
	threads = 4;
	% digit 0
	ds_digit_0_hsf0 = datastore("by_field/hsf_0/digit/30/30_*.png");
	ds_digit_0_hsf1 = datastore("by_field/hsf_1/digit/30/30_*.png");
	ds_digit_0_hsf2 = datastore("by_field/hsf_2/digit/30/30_*.png");
	ds_digit_0_hsf3 = datastore("by_field/hsf_3/digit/30/30_*.png");
	ds_digit_0_hsf4 = datastore("by_field/hsf_4/digit/30/30_*.png");
	ds_digit_0_hsf6 = datastore("by_field/hsf_6/digit/30/30_*.png");
	ds_digit_0_hsf7 = datastore("by_field/hsf_7/digit/30/30_*.png");
	% digit 1
	ds_digit_1_hsf0 = datastore("by_field/hsf_0/digit/31/31_*.png");
	ds_digit_1_hsf1 = datastore("by_field/hsf_1/digit/31/31_*.png");
	ds_digit_1_hsf2 = datastore("by_field/hsf_2/digit/31/31_*.png");
	ds_digit_1_hsf3 = datastore("by_field/hsf_3/digit/31/31_*.png");
	ds_digit_1_hsf4 = datastore("by_field/hsf_4/digit/31/31_*.png");
	ds_digit_1_hsf6 = datastore("by_field/hsf_6/digit/31/31_*.png");
	ds_digit_1_hsf7 = datastore("by_field/hsf_7/digit/31/31_*.png");
	% digit 2
	ds_digit_2_hsf0 = datastore("by_field/hsf_0/digit/32/32_*.png");
	ds_digit_2_hsf1 = datastore("by_field/hsf_1/digit/32/32_*.png");
	ds_digit_2_hsf2 = datastore("by_field/hsf_2/digit/32/32_*.png");
	ds_digit_2_hsf3 = datastore("by_field/hsf_3/digit/32/32_*.png");
	ds_digit_2_hsf4 = datastore("by_field/hsf_4/digit/32/32_*.png");
	ds_digit_2_hsf6 = datastore("by_field/hsf_6/digit/32/32_*.png");
	ds_digit_2_hsf7 = datastore("by_field/hsf_7/digit/32/32_*.png");
	% digit 3
	ds_digit_3_hsf0 = datastore("by_field/hsf_0/digit/33/33_*.png");
	ds_digit_3_hsf1 = datastore("by_field/hsf_1/digit/33/33_*.png");
	ds_digit_3_hsf2 = datastore("by_field/hsf_2/digit/33/33_*.png");
	ds_digit_3_hsf3 = datastore("by_field/hsf_3/digit/33/33_*.png");
	ds_digit_3_hsf4 = datastore("by_field/hsf_4/digit/33/33_*.png");
	ds_digit_3_hsf6 = datastore("by_field/hsf_6/digit/33/33_*.png");
	ds_digit_3_hsf7 = datastore("by_field/hsf_7/digit/33/33_*.png");
	% digit 4
	ds_digit_4_hsf0 = datastore("by_field/hsf_0/digit/34/34_*.png");
	ds_digit_4_hsf1 = datastore("by_field/hsf_1/digit/34/34_*.png");
	ds_digit_4_hsf2 = datastore("by_field/hsf_2/digit/34/34_*.png");
	ds_digit_4_hsf3 = datastore("by_field/hsf_3/digit/34/34_*.png");
	ds_digit_4_hsf4 = datastore("by_field/hsf_4/digit/34/34_*.png");
	ds_digit_4_hsf6 = datastore("by_field/hsf_6/digit/34/34_*.png");
	ds_digit_4_hsf7 = datastore("by_field/hsf_7/digit/34/34_*.png");
	% digit 5
	ds_digit_5_hsf0 = datastore("by_field/hsf_0/digit/35/35_*.png");
	ds_digit_5_hsf1 = datastore("by_field/hsf_1/digit/35/35_*.png");
	ds_digit_5_hsf2 = datastore("by_field/hsf_2/digit/35/35_*.png");
	ds_digit_5_hsf3 = datastore("by_field/hsf_3/digit/35/35_*.png");
	ds_digit_5_hsf4 = datastore("by_field/hsf_4/digit/35/35_*.png");
	ds_digit_5_hsf6 = datastore("by_field/hsf_6/digit/35/35_*.png");
	ds_digit_5_hsf7 = datastore("by_field/hsf_7/digit/35/35_*.png");
	% digit 6
	ds_digit_6_hsf0 = datastore("by_field/hsf_0/digit/36/36_*.png");
	ds_digit_6_hsf1 = datastore("by_field/hsf_1/digit/36/36_*.png");
	ds_digit_6_hsf2 = datastore("by_field/hsf_2/digit/36/36_*.png");
	ds_digit_6_hsf3 = datastore("by_field/hsf_3/digit/36/36_*.png");
	ds_digit_6_hsf4 = datastore("by_field/hsf_4/digit/36/36_*.png");
	ds_digit_6_hsf6 = datastore("by_field/hsf_6/digit/36/36_*.png");
	ds_digit_6_hsf7 = datastore("by_field/hsf_7/digit/36/36_*.png");
	% digit 7
	ds_digit_7_hsf0 = datastore("by_field/hsf_0/digit/37/37_*.png");
	ds_digit_7_hsf1 = datastore("by_field/hsf_1/digit/37/37_*.png");
	ds_digit_7_hsf2 = datastore("by_field/hsf_2/digit/37/37_*.png");
	ds_digit_7_hsf3 = datastore("by_field/hsf_3/digit/37/37_*.png");
	ds_digit_7_hsf4 = datastore("by_field/hsf_4/digit/37/37_*.png");
	ds_digit_7_hsf6 = datastore("by_field/hsf_6/digit/37/37_*.png");
	ds_digit_7_hsf7 = datastore("by_field/hsf_7/digit/37/37_*.png");
	% digit 8
	ds_digit_8_hsf0 = datastore("by_field/hsf_0/digit/38/38_*.png");
	ds_digit_8_hsf1 = datastore("by_field/hsf_1/digit/38/38_*.png");
	ds_digit_8_hsf2 = datastore("by_field/hsf_2/digit/38/38_*.png");
	ds_digit_8_hsf3 = datastore("by_field/hsf_3/digit/38/38_*.png");
	ds_digit_8_hsf4 = datastore("by_field/hsf_4/digit/38/38_*.png");
	ds_digit_8_hsf6 = datastore("by_field/hsf_6/digit/38/38_*.png");
	ds_digit_8_hsf7 = datastore("by_field/hsf_7/digit/38/38_*.png");
	% digit 9
	ds_digit_9_hsf0 = datastore("by_field/hsf_0/digit/39/39_*.png");
	ds_digit_9_hsf1 = datastore("by_field/hsf_1/digit/39/39_*.png");
	ds_digit_9_hsf2 = datastore("by_field/hsf_2/digit/39/39_*.png");
	ds_digit_9_hsf3 = datastore("by_field/hsf_3/digit/39/39_*.png");
	ds_digit_9_hsf4 = datastore("by_field/hsf_4/digit/39/39_*.png");
	ds_digit_9_hsf6 = datastore("by_field/hsf_6/digit/39/39_*.png");
	ds_digit_9_hsf7 = datastore("by_field/hsf_7/digit/39/39_*.png");

	% combine 0
	ds0 = combine(ds_digit_0_hsf0, ...
       		ds_digit_0_hsf1, ...
	       	ds_digit_0_hsf2, ...
	       	ds_digit_0_hsf3, ...
		ds_digit_0_hsf4, ...
		ds_digit_0_hsf6, ...
		ds_digit_0_hsf7, ...
		ReadOrder="sequential" ...
	);
	% combine 1
	ds1 = combine(ds_digit_1_hsf0, ...
       		ds_digit_1_hsf1, ...
	       	ds_digit_1_hsf2, ...
	       	ds_digit_1_hsf3, ...
		ds_digit_1_hsf4, ...
		ds_digit_1_hsf6, ...
		ds_digit_1_hsf7, ...
		ReadOrder="sequential" ...
	);
	% combine 2
	ds2 = combine(ds_digit_2_hsf0, ...
       		ds_digit_2_hsf1, ...
	       	ds_digit_2_hsf2, ...
	       	ds_digit_2_hsf3, ...
		ds_digit_2_hsf4, ...
		ds_digit_2_hsf6, ...
		ds_digit_2_hsf7, ...
		ReadOrder="sequential" ...
	);
	% combine 3
	ds3 = combine(ds_digit_3_hsf0, ...
       		ds_digit_3_hsf1, ...
	       	ds_digit_3_hsf2, ...
	       	ds_digit_3_hsf3, ...
		ds_digit_3_hsf4, ...
		ds_digit_3_hsf6, ...
		ds_digit_3_hsf7, ...
		ReadOrder="sequential" ...
	);
	% combine 4
	ds4 = combine(ds_digit_4_hsf0, ...
       		ds_digit_4_hsf1, ...
	       	ds_digit_4_hsf2, ...
	       	ds_digit_4_hsf3, ...
		ds_digit_4_hsf4, ...
		ds_digit_4_hsf6, ...
		ds_digit_4_hsf7, ...
		ReadOrder="sequential" ...
	);
	% combine 5
	ds5 = combine(ds_digit_5_hsf0, ...
       		ds_digit_5_hsf1, ...
	       	ds_digit_5_hsf2, ...
	       	ds_digit_5_hsf3, ...
		ds_digit_5_hsf4, ...
		ds_digit_5_hsf6, ...
		ds_digit_5_hsf7, ...
		ReadOrder="sequential" ...
	);
	% combine 6
	ds6 = combine(ds_digit_6_hsf0, ...
       		ds_digit_6_hsf1, ...
	       	ds_digit_6_hsf2, ...
	       	ds_digit_6_hsf3, ...
		ds_digit_6_hsf4, ...
		ds_digit_6_hsf6, ...
		ds_digit_6_hsf7, ...
		ReadOrder="sequential" ...
	);
	% combine 7
	ds7 = combine(ds_digit_7_hsf0, ...
       		ds_digit_7_hsf1, ...
	       	ds_digit_7_hsf2, ...
	       	ds_digit_7_hsf3, ...
		ds_digit_7_hsf4, ...
		ds_digit_7_hsf6, ...
		ds_digit_7_hsf7, ...
		ReadOrder="sequential" ...
	);
	% combine 8
	ds8 = combine(ds_digit_8_hsf0, ...
       		ds_digit_8_hsf1, ...
	       	ds_digit_8_hsf2, ...
	       	ds_digit_8_hsf3, ...
		ds_digit_8_hsf4, ...
		ds_digit_8_hsf6, ...
		ds_digit_8_hsf7, ...
		ReadOrder="sequential" ...
	);
	% combine 9
	ds9 = combine(ds_digit_9_hsf0, ...
       		ds_digit_9_hsf1, ...
	       	ds_digit_9_hsf2, ...
	       	ds_digit_9_hsf3, ...
		ds_digit_9_hsf4, ...
		ds_digit_9_hsf6, ...
		ds_digit_9_hsf7, ...
		ReadOrder="sequential" ...
	);
	rawdata = {ds0, ds1, ds2, ds3, ds4, ds5, ds6, ds7, ds8, ds9};
	!rm -rf trainingdata
	!mkdir trainingdata
	!mkdir trainingdata/0
	!mkdir trainingdata/1
	!mkdir trainingdata/2
	!mkdir trainingdata/3
	!mkdir trainingdata/4
	!mkdir trainingdata/5
	!mkdir trainingdata/6
	!mkdir trainingdata/7
	!mkdir trainingdata/8
	!mkdir trainingdata/9
	parfor (i = 1:40363, threads); imwrite(cell2mat(read(rawdata{1})), "trainingdata/0/"+i+".png", "png"); end;
	disp("Digit 0 transformed");
	parfor (i = 1:44704, threads); imwrite(cell2mat(read(rawdata{2})), "trainingdata/1/"+i+".png", "png"); end;
	disp("Digit 1 transformed");
	parfor (i = 1:40072, threads); imwrite(cell2mat(read(rawdata{3})), "trainingdata/2/"+i+".png", "png"); end;
	disp("Digit 2 transformed");
	parfor (i = 1:41112, threads); imwrite(cell2mat(read(rawdata{4})), "trainingdata/3/"+i+".png", "png"); end;
	disp("Digit 3 transformed");
	parfor (i = 1:39154, threads); imwrite(cell2mat(read(rawdata{5})), "trainingdata/4/"+i+".png", "png"); end;
	disp("Digit 4 transformed");
	parfor (i = 1:36606, threads); imwrite(cell2mat(read(rawdata{6})), "trainingdata/5/"+i+".png", "png"); end;
	disp("Digit 5 transformed");
	parfor (i = 1:39937, threads); imwrite(cell2mat(read(rawdata{7})), "trainingdata/6/"+i+".png", "png"); end;
	disp("Digit 6 transformed");
	parfor (i = 1:41893, threads); imwrite(cell2mat(read(rawdata{8})), "trainingdata/7/"+i+".png", "png"); end;
	disp("Digit 7 transformed");
	parfor (i = 1:39579, threads); imwrite(cell2mat(read(rawdata{9})), "trainingdata/8/"+i+".png", "png"); end;
	disp("Digit 8 transformed");
	parfor (i = 1:39433, threads); imwrite(cell2mat(read(rawdata{10})), "trainingdata/9/"+i+".png", "png"); end;
	disp("Digit 9 transformed");
	%read new data and return datastore for it.
end

function data = getData()
	data = imageDatastore("trainingdata", IncludeSubfolders=true, LabelSource="foldernames");
end

clear all;
close all;
clc;
main();
